export const DEFAULT_RESOURCE_KEY = 'work'

export const RESOURCE_CONFIG = {
  services: {
    label: 'Services',
    singularLabel: 'Service',
    endpoint: '/api/services/admin',
    emptyForm: {
      title: '',
      description: '',
      icon: 'window',
      order: 1,
      isActive: true,
    },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      {
        name: 'icon',
        label: 'Icon',
        type: 'select',
        required: true,
        options: ['window', 'screen', 'tag', 'spark'],
      },
      { name: 'order', label: 'Order', type: 'number', min: 0, required: true },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    previewFields: ['title', 'description', 'icon'],
  },
  work: {
    label: 'Work',
    singularLabel: 'Work Item',
    endpoint: '/api/work/admin',
    emptyForm: {
      key: '',
      category: '',
      title: '',
      subtitle: '',
      fallback: '#d9dee6',
      image: "url('https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80')",
      imagePublicId: '',
      order: 1,
      isActive: true,
    },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'category', label: 'Category', type: 'text', required: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtitle', type: 'textarea', required: true },
      { name: 'fallback', label: 'Fallback Color', type: 'text', required: true },
      { name: 'image', label: 'Image (CSS background value)', type: 'text', required: true },
      { name: 'imagePublicId', label: 'Image Public ID', type: 'text' },
      { name: 'order', label: 'Order', type: 'number', min: 0, required: true },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    previewFields: ['title', 'category', 'subtitle', 'key'],
  },
  testimonials: {
    label: 'Testimonials',
    singularLabel: 'Testimonial',
    endpoint: '/api/testimonials/admin',
    emptyForm: {
      quote: '',
      name: '',
      role: '',
      avatar: '',
      order: 1,
      isActive: true,
    },
    fields: [
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'role', label: 'Role', type: 'text', required: true },
      { name: 'avatar', label: 'Avatar URL', type: 'text', required: true },
      { name: 'order', label: 'Order', type: 'number', min: 0, required: true },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    previewFields: ['name', 'role', 'quote'],
  },
  faqs: {
    label: 'FAQs',
    singularLabel: 'FAQ',
    endpoint: '/api/faqs/admin',
    emptyForm: {
      key: '',
      question: '',
      answer: '',
      order: 1,
      isActive: true,
    },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      { name: 'order', label: 'Order', type: 'number', min: 0, required: true },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    previewFields: ['question', 'answer', 'key'],
  },
}
